name: ac_inet_connectivity_checker
description: A simple, cancellable and stateless Internet connectivity checker which do not depend on any protocol
version: 0.2.0
repository: https://github.com/anthochamp/dart-inet-connectivity-checker

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  async: ^2.10.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  ac_lints: ^0.4.0
  build_runner: ^2.3.3
  freezed: ^2.5.8
  import_sorter: ^4.6.0
  test: ^1.24.2
